### ISSUE TITLE
Window/Tab title not updated with JavaScript causing Speculative Parsing

### ISSUE THREAD

**Issue by stonecrusher** [erichgoldman/add-url-to-window-title#11]
Hey,
just another example with the title not updating. I use Firefox 45.0.1.
If i disable JS on www.mv-werneck.de everything is fine. If it is enabled, the window title will not update when clicking through the navigation (look for menu point "Verein", where you can toggle visibility somewhere in the content).

There is a little script that uses document.write() to write the open tag of an div-element, but doesn't close it. It is closed later in another <script></script> section. I think this is done to make the content in the div-element also appear if you disable JS.
The unclosed element causes [Speculative Parsing](http://taligarsiel.com/Projects/howbrowserswork1.htm#Speculative_parsing) in Firefox to fail, so it needs to be parsed again. That might be the reason for that bug?
I hope it helps a bit.

The bug is also still present for me with the sites mentioned in #6 and #7.
Best greets
Stonecrusher

/edit: Console in firefox suggests [this](https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing). It's made for the webmaster, but still may be useful.

**Comment by erichgoldman** [comment]
If there is a bug in another script on the page, that will cause this plugin to have issues as well. I am considering an exclusion list for future versions.

**Comment by stonecrusher** [comment]
Ok the source code of the page has changed meanwhile. There's no more notification in the FF developer console.
So it seems that document.write() and speculative parsing were innocent.
I thought i could help, but I have no clue...

Yep, an exclusion list doesn't solve the problem but is more practical for users in most cases.
Thanks anyway!

**Comment by erichgoldman** [comment]
Thank you for the update. Its hard to debug and make changes on a per-site basis. JavaScript doesn't have to always function properly or nicely with others, so its always a struggle. It would be better if we could get the title and url information from a lower level of the browser, but the direction is to give addon developers less low level access across browsers.

**Comment by stonecrusher** [comment]
Obsolete due to new WebExtension requirements.
And I want to clean my open issues list.
