### ISSUE TITLE
Unicode Issue

### ISSUE THREAD

**Issue by dufferzafar** [erichgoldman/add-url-to-window-title#12]
The URL seems to get html escaped when added to the title bar.

For eg. go to url: https://www.candyjapan.com/口

And see the title! 

It displays for me as : `口 | https://www.candyjapan.com/%E5%8F%A3 - Mozilla Firefox`

I've set `|` as the separator.

**Comment by erichgoldman** [comment]
This looks to be a HTML encoding of the non ASCII text. This escaping is performed by FireFox itself and not the extension. See the notes for the [sanitizer function in add-url-to-title.js:250](https://github.com/erichgoldman/add-url-to-window-title/blob/master/data/add-url-to-title.js#L250).

However, the URL encoding will be the same for any given kanji or other non-latin characters, so for matching purposes in KeePass it should still work.

I will see if I can find the specific reference about this functionality, I believe it automatically does encoding when you perform `document.title = foo`. Even if it displays the character properly in the address bar itself, I believe FireFox always stores it as an escaped string. 

It may be possible to decode it when setting the title, however, I will need to check on any possible security concerns with doing that.

**Comment by erichgoldman** [comment]
In doing some further research I came across this [FireFox Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=552273#c0)

In `about:config` I made the following changes:

> set `network.standard-url.encode-utf8` to `false`
> 
> set `network.standard-url.escape-utf8` to `false`

then restart FireFox and try to load the URL again, now it shows properly. This seems to be working most of the time, but one or two times it still did encoding for me. 

I tested some examples from: https://www.w3.org/International/articles/idn-and-iri/ and  http://www.i18nguy.com/markup/idna-examples.html and it seems to generally show the original characters without encoding.

Please note, there may be a security or functionality impact if you change these settings. I do not plan on adding code to change this functionality in the extension and leave it as a user choice with the FireFox settings.

Can you please test and let me know if this resolves your issue?

Potentially Related:
 - http://superuser.com/questions/480692/copying-unicode-symbols-from-firefox-address-bar-as-is

**Comment by dufferzafar** [comment]
Yes, changing those settings does fix things for me. Thanks!
