### ISSUE TITLE
seems broken with firefox v52.0.2

### ISSUE THREAD

**Issue by Tormen** [erichgoldman/add-url-to-window-title#20]
Hi,
I am a long time user of your addon. Crucial for me with KeePassX under linux.
Unfortunately it seemed to have stopped working since firefox update to v52.0.2
I can't access it's "preferences" anymore (so on about:addons, I select the addon, then click the "Preferences" button, then a page opens but there are no preferences anymore, just the addons description and the "donate" button...).
And most of all: It does not add the url anymore to the window title (no matter which site).

Could you help?

Of course this would be the perfect moment to donate... but the DONATE function is broken :(((
See my bug-report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1354479

Tormen

**Comment by stonecrusher** [comment]
Still works for me (Firefox 52.0.2 32-bit).
Preferences are at the bottom of the addon-page (just scroll down).
Did you try if it works with a fresh profile? If it does, it might just interfere with some other addon.

**Comment by Tormen** [comment]
Hi. Thanks a lot for your response!

I just tried it again. And it works again.
Hun. Not sure what happened, but I am sure to have scrolled down before I wrote this bug-report ;)
... I might have done a system-update inbetween.
Also I will try to not be too lazy and check an empty profile quickly next time - you are right, that this is important.
Aaaanyhow, I close this issue now.
