### ISSUE TITLE
Extension options not available in Add-ons Manger (and the extension does not work)

### ISSUE THREAD

**Issue by Jon999999** [erichgoldman/add-url-to-window-title#21]
After working properly for some time, URLs no longer appear in the Firefox title bar. Clicking the Option button for the extension in the Add-ons Manager just brings up the description of the extension, without the Settings section. Restarting the browser usually doesn't work, but sometimes it does.

![image](https://user-images.githubusercontent.com/31597590/30006023-5b3b68ba-90bd-11e7-80e9-6cde50737da2.png)

**Comment by alerque** [comment]
I am not able to duplicate this problem. What version of Firefox are you running and on what operating system are you running it?

**Comment by Jon999999** [comment]
I was on 55 (64-bit) but have downgraded since to 52 ESR in the hope that
that would fix it, but it did not.

Windows 10 Pro 64-bit.

The issue happens most times that I launch FF, but occasionally (rarely),
it works.

**Comment by alerque** [comment]
This might be platform specific then (I'm on Linux and rely on this constantly for my password manager to match entries), but more likely I suspect an interaction with some _other_ extension you have running. Have you tried this with all other extensions disabled?

**Comment by Jon999999** [comment]
Caleb,

 

Yes, I agree.  The conflict appears to be between Add URL to Window Title (ver 1.03) and Tab Mix Plus (ver 0.5.0.4).  I also note a similar issue between Flash Video Downloader - YouTube Download [4K] (ver 15.0.19) and Tab Mix Plus.

 

With all other extensions disabled (+ is enabled, - is disabled):

 

AddURL     FVD       TMP         Result

--------  --------  --------  -----------------------

   +         -         -      AddURL works

   +         -         +      AddURL breaks

   +         +         -      AddURL works, FVD works

   +         +         +      AddURL breaks, FVD breaks

   -         +         -      FVD works

   -         +         +      FVD breaks

--------  --------  --------  -----------------------

 

Note than when first disabling TMP and restarting, the other extensions sometimes work properly the first time, but when FF is again restarted, they stop working usually -- but sometimes when starting FF again, they randomly work.  Once they work in a given FF instance, they keep working at leastuntil FF is restarted again.

 

So it appears that TMP is somehow interfering with AddURL and FVD starting up, as if it were a race condition.

 

I will report this through the help pages of the other two extensions, if I can.  Given how common TMP is, have you not seen this issue before?

 

 

Environment:

Windows 10 Pro 64-bit Creators Update, version 1703 (build 10.0.15063)

Firefox ESR 64-bit version 52.3.0 (previously also observed with Firefox 64-bit ver 55.0.3)

Add URL to Window Title, version 1.03

Tab Mix Plus, version 0.5.0.4

Flash Video Downloader - YouTube Download [4K], version 15.0.19

all other extensions disabled, other than the three built-in Plugins (OpenH264, Flash, Widevine)

**Comment by Jon999999** [comment]
Caleb,

Yes, I agree. There appears to be a conflict between Add URL to Window Title (ver 1.03) and Tab Mix Plus (ver 0.5.0.4).  I also note a similar issue between Flash Video Downloader - YouTube Download [4K] (ver 15.0.19) and Tab Mix Plus.

When Tab Mix Plus is enabled with either or both of the other extensions, TMP works but the other extension(s) do not.  AddURL stops adding the URL to the title bar and its small options section (accessible through its Options button in the Tools > Add-ons > Extensions page) disappears.  FVD disappears from the toolbar entirely.

Note than when first enabling TMP and restarting, the other extensions sometimes work properly the first time, but when FF is again restarted, they stop working usually -- but sometimes when starting FF again, they randomly work.  Once they work in a given FF instance, they keep working at least until FF is restarted again. When disabling TMP, the other extensions start working on the first restart.

So it appears that TMP is somehow interfering with AddURL and FVD starting up, as in a race condition.

TESTING:
With all other extensions disabled (+ is enabled, - is disabled):

```
AddURL     FVD       TMP         Result
--------  --------  --------  -----------------------
   +         -         -      AddURL works
   +         -         +      AddURL breaks
   +         +         -      AddURL works, FVD works
   +         +         +      AddURL breaks, FVD breaks
   -         +         -      FVD works
   -         +         +      FVD breaks
--------  --------  --------  -----------------------
```

I am reporting this through the help pages of the other two extensions as well. but given how common TMP is, have you not heard something like this before?

Thank you.



ENVIRONMENT:
Windows 10 Pro 64-bit Creators Update, version 1703 (build 10.0.15063)
Firefox ESR 64-bit version 52.3.0 (previously also observed with Firefox 64-bit ver 55.0.3)
Add URL to Window Title, version 1.03
Tab Mix Plus, version 0.5.0.4
Flash Video Downloader - YouTube Download [4K], version 15.0.19
all other extensions disabled, other than the three built-in Plugins (OpenH264, Flash, Widevine)

**Comment by alerque** [comment]
> I am reporting this through the help pages of the other two extensions as well. but given how common TMP is, have you not heard something like this before?

Yes. It sounds like _Tab Mix Plus_ is your culprit and they are doing something fairly invasive messing with the way Firefox works and not providing the same interfaces and structure the way other extensions expect to find it. This is one kind of thing the upcoming WebExtensions system is supposed to solve: by not providing such low level access and making sure the same APIs  are available to all extensions these sort of nasty interactions should be minimized. This is also why a lot of extension developers are so upset: some of the power to change basic bits about how the browser works is being taken away from them.

For now it sounds to me like a bug report on _TMP_ is about all you can do. The Flash video thing isn't even worth bothering with: Flash should have died a decade ago, but it's been officially EOL'ed and won't be usable in upcoming browser versions anyway, any extensions that mess with it are probably not worth fixing to be WexExtensions.

**Comment by erichgoldman** [comment]
@alerque Thanks for providing all of the above great troubleshooting support.

@Jon999999 I believe at some point I was running both of those extensions on my personal installation, but I do not now. I will try to take a look in the next couple of weeks, but since this version is EOL, as I will eventually figure out WebExtensions, I am not going to try to add code to compensate for other extensions. In the WebExtension's world there is no standard API for managing configuration options, you just create another page for user's to access that sets the variables.

For your own personal usage, you could try to change the [settings file](https://github.com/erichgoldman/add-url-to-window-title/blob/master/package.json#L18) manually and then install your own version from source instead of using the on Mozilla's site.
