### ISSUE TITLE
Firefox 57 support?

### ISSUE THREAD

**Issue by joeto0** [erichgoldman/add-url-to-window-title#22]
Hi,
First of all really nice and helpful extension, any chance to make it works with 57? and any estimation when?

Thank you in advance.

**Comment by erichgoldman** [comment]
Hello,

I have recently started the work to port this extension to Chrome style add-ons. I am minimizing the amount of non content script functions needed. There are some differences in Chrome vs FireFox API I need to test, but I plan to release at least a Chrome version before the new year if time allows.

**Comment by erichgoldman** [comment]
I just pushed the code here for the new Chrome style addon and it should also work with Firefox. I am going to do some testing and will update here.

**Comment by erichgoldman** [comment]
The new extension is running in modern Firefox and has been updated on the [official AMO](https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/)
