### ISSUE TITLE
broken markdown at https://github.com/erichgoldman/add-url-to-window-title/wiki/Recommended-Auto-Type-Settings-for-KeePass

### ISSUE THREAD

**Issue by matkoniecz** [erichgoldman/add-url-to-window-title#23]
First heading renders as an unformatted code

![selection_001](https://user-images.githubusercontent.com/899988/41275658-e8b62d96-6e21-11e8-978d-9fd1278d9d99.png)

in https://github.com/erichgoldman/add-url-to-window-title/wiki/Recommended-Auto-Type-Settings-for-KeePass

**Comment by erichgoldman** [comment]
Fixed, and updated, thank you!
