### ISSUE TITLE
Full URL mode should show the protocol

### ISSUE THREAD

**Issue by erichgoldman** [erichgoldman/add-url-to-window-title#24]
When "Show the full URL?" is checked yes, it should include the protocol (`https://`) per https://github.com/erichgoldman/add-url-to-window-title/blob/web-extension/managetitle.js#L204 by calling `document.URL` however, this is being clipped.

Fixing this could break some people's auto-type rules if they made their regex already and didn't include the protocol. We could make this option into a drop down multiple choice instead of a boolean. Most likely outcome will be that some users autotypes will break.

**Comment by erichgoldman** [comment]
@lieryan Can you please confirm that you have selected the option for "Show the full URL?" and then hit the save button at the bottom of the options. I had one test where this was breaking as your described, but now I cannot replicate and I have the protocol as long as I have this checkbox clicked and the setting saved. Please check your settings and let me know.

**Comment by stonecrusher** [comment]
I also cannot reproduce (FF74.0, AU2WT 2.2.1).
`document.URL` gives the full URI including protocol, thus "Show the full URL" is working as expected. 
No issue.
