### ISSUE TITLE
Saving settings to storage (i.e. ~/.mozilla/firefox/profile/browser-extension-data/)

### ISSUE THREAD

**Issue by michalrus** [erichgoldman/add-url-to-window-title#27]
Other extensions save their settings to `storage`, and then it’s easy to keep those settings in dotfiles.

However I don’t see a directory for `add-url-to-window-title` in there:

```
% ls -l ~/.mozilla/firefox/profile.default/browser-extension-data 
total 16
drwx------ 2 m users 4096 Feb 18 05:09 https-everywhere@eff.org
drwx------ 2 m users 4096 Feb 19 01:23 screenshots@mozilla.org
drwx------ 2 m users 4096 Feb 19 01:34 uBlock0@raymondhill.net
drwx------ 2 m users 4096 Feb 19 01:23 uMatrix@raymondhill.net

%
```

It would be super-cool to be able to keep your settings in dotfiles, too. =)

**Comment by erichgoldman** [comment]
@michalrus Returning to this issue. I recall looking into this in the past and either not finding good documentation or determining it was overkill given there are only 3 options for the extension. Therefore, I am labeling this at `wontfix` and I am going to close this request.
