### ISSUE TITLE
Feature Request: Remove Trailing Slash from hostname

### ISSUE THREAD

**Issue by Aternus** [erichgoldman/add-url-to-window-title#29]
It would be great to have a setting that when enabled removes the trailing slash from the hostname so that Window titles look pretty while switching tabs/windows.

While we're at it, removing the "www." part for hostnames will make it even more awesome.

I can help with writing the regexes for that if you'd like 🙏

**Comment by erichgoldman** [comment]
A given website at `https://www.example.com` and `https://example.com` [are not necessarily the same website](https://computer.howstuffworks.com/internet/basics/question180.htm); while this is customary, it is not always the case. Users may not want to automatically strip `www` if they are doing testing (did my redirect rule trigger properly) or to prevent accidentally activating on the wrong website. 

There are also implications in the update algorithm within the extension that would make this very complicated. You should be able to use a [regex to match](https://stackoverflow.com/a/2038030/13221925) in KeePass, and if you are using another tool it likely can do something similar.

As for the trailing slash, there are also non cosmetic reasons to keep the trailing slash. For example, if you match on `example.com` it might also match on `example.com.evil.com` or `google.com-evilsite.com`. This is an [explicit decision in the code](https://github.com/erichgoldman/add-url-to-window-title/blob/9a85fed0f2351728ee50ff9169c98000bc693b65/managetitle.js#L199-L202).
