### ISSUE TITLE
couldn't install this from the chrome web store

### ISSUE THREAD

**Issue by mcarifio** [erichgoldman/add-url-to-window-title#30]
I got some kind of permissions error. So I installed it "unpacked" after cloning the repo. Unfortunately, after that I can't reproduce the error so I can't give you much to work with.

**Comment by erichgoldman** [comment]
@mcarifio  can you provide some additional detail here? The extension showed up in the Chrome Webstore, allowed you to download, and then you received the error in your browser or you were never able to download in the first place?

Can you please provide operating system, browser version information, etc.

To confirm, when you install from source you did not receive this error?

**Comment by mcarifio** [comment]
Yeah, unfortunately I'm not going to be able to give you a lot of useful information here. I almost didn't create an issue because of this. I also can't reproduce the error even when I change accounts in the chromium-browser.

That said, the behavior was that I installed https://chrome.google.com/webstore/detail/add-url-to-window-title/ndiaggkadcioihmhghipjmgfeamgjeoi?hl=en a few times and kept getting a message along the lines of `98323873847384.crx terminated, permission denied`. So it could just be that webstore was offline. Based on the message, I don't know if a .crx arrived (nothing in ~/Downloads) to be installed.

When I install from source, no error. When I install in vivaldi, opera or brave, no error and works. Here's the os, browser stuff:

```bash
$ lsb_release -a
LSB Version:	core-11.0.1ubuntu1-noarch:printing-11.0.1ubuntu1-noarch:security-11.0.1ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

$ chromium-browser --version
Chromium 81.0.4044.92 snap

```

**Comment by mcarifio** [comment]
I'm going to close this myself so as not to waste your time. If someone else has an odd experience like it, then you have somewhere to capture future data.
