### ISSUE TITLE
How do I add the current account/profile to the title?

### ISSUE THREAD

**Issue by mcarifio** [erichgoldman/add-url-to-window-title#31]
This is a little off topic. Reading the code, it looks like I can add "more stuff" to the title by modifying `titleFormatter()`. I'd like to add the local chrome user (as in https://www.pcworld.com/article/2089364/how-to-create-and-manage-multiple-user-profiles-in-chrome.html) to the title, since it will help me select the right window when tabbing through several browser windows. I can't find the code to extract it, however. Can that information be obtained from the  extension api?

Cool extension btw. Thank you.

**Comment by erichgoldman** [comment]
I don't believe their is such an API. However, you can use a content script an modify anything on a page.

Technically you could probably use fetch or something to call a Google service or web page and scrape that value. If you are authenticated in your browser, you should have the proper cookies, etc to make the request. e.g., perhaps you could query this page: `https://myaccount.google.com/personal-info` and then scrape some identifier, change your favicon to the account icon, or something like that. You could also set which pages/domains the extension applies so it would only be on the pages you need.

I don't use react, and neither do you, but the logic should be the same as described here: https://levelup.gitconnected.com/how-to-use-background-script-to-fetch-data-in-chrome-extension-ef9d7f69625d

Not sure if you want a corp account or individual account, but I know there are user management APIs for corp accounts.

**Comment by erichgoldman** [comment]
```
fetch('https://myaccount.google.com/personal-info').then(function (response) {
  return response.text();
}).then(function (html) {
  let doc = new DOMParser().parseFromString(html, 'text/html');
  let nameData = doc.querySelector("a.gb_D.gb_Ra").getAttribute('aria-label');
  console.info(nameData);
}).catch(function (err) {
  console.warn('Something went wrong.', err);
});
```
In the above I use `fetch()` to query the google acount page, I put the response in a virtual html document, I then query on a field where I found my name while inspectng the source. I am not sure if these variables are consistent over time or session as i just did a quick test. Since you probably know your `nameData` value for all your acccount you could then modify your title bar similar to this extension or extend this extension in a similar manner. However, be aware that having two extensions that both change the title could result in a situation where they keep changing as they are tracking each other.

**Comment by mcarifio** [comment]
In some cases, I wouldn't be logged in. It looks like I can get the name via Process.profile https://developer.chrome.com/extensions/processes#method-getProcessIdForTab, so something like current tab -> associated process -> process.profile (as a string). I don't have a lot of extension chops, but I'll give it a go.

Client-side js programming is jibberish. Good lord.

**Comment by erichgoldman** [comment]
`Repo Maintenance`  Because this is a very specific need and not a broad-facing  use case this is a `wontfix` issue. Hopefully the discussion and research provided some pathway forward. I am closing this issue to reduce lingering open issues.
