### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by ghost** [erichgoldman/add-url-to-window-title#36]
FF 90.0.1 (64-bit) on FreeBSD.
No effect at all after plugin installation. Restarting FF does not change anything.
Any ideas?

**Comment by erichgoldman** [comment]
@SkunkBSD did this previously work in another version of FF ?

You can use devtools to investigate any console errors or the running of the program. Please check out this [extension debugging guide](https://extensionworkshop.com/documentation/develop/debugging/). If there is a specific error, you should see some output.

I would spin up an instance without other extensions running at the same time. It is possible there is some conflict with the operation of another extension you might be using.

You can also try looking at the various extension settings. If the extension settings load and you can change them (a) likely means the extension is running properly (b) some setting may refresh things?

**Comment by ghost** [comment]
This is my first attempt of installing the extension, to have more meaningful information instead of only "Mozilla Firefox" in the title bar.

Reading the debugging guide, I find that instead of the browser console, a download history window opens.
No other extensions active. This installation is 1 year old, and there are more than a dozen windows open which I cannot dump right now. So I guess the problem might be caused by a FF that got rotten over time.

Today I have installed a fresh FreeBSD 13-RELEASE-p6 with FF 91.4 ESR, and from this maiden installation your extension works just fine :)

Will move to that new workstation soon, and when I do no longer need the tabs on the old one, I'll try a clean start of the old FF to see what happens with the debug tools, if they will indicate anything wrong.
Will report back soon.

**Comment by erichgoldman** [comment]
You may be able to find an extension that an go through each window and make an export of all your tabs with title + URL. I am using a Chromium based browser for the past few years, so I do not have a FF recommendation.

Glad to hear it is working on the fresh install.
