### ISSUE TITLE
Window/Tab title not updated properly

### ISSUE THREAD

**Issue by admirabilis** [erichgoldman/add-url-to-window-title#6]
Hello, Erich! Thank you for this great extension!

On many websites I have noticed that with this extension enabled, the window title many times is not updated properly. For example:
- Visit: https://addons.mozilla.org/en-US/firefox/
- Title: Add-ons for Firefox - addons.mozilla.org/ - Firefox
- Click on "Adblock Plus" at the "Most Popular" sidebar
- Title: Add-ons for Firefox - addons.mozilla.org/ - Firefox

Now disable the extension:
- Visit: https://addons.mozilla.org/en-US/firefox/
- Title: Add-ons for Firefox - Firefox
- Click on "Adblock Plus" at the "Most Popular" sidebar
- Title: **Adblock Plus ::** Add-ons for Firefox - Firefox

This is just a harmless example. But sometimes I search for something on my search engine, for example "Firefox 41", and then use the search engine's own form to query for another unrelated word (eg. "Chocolate Ice Cream"), but the title remains the old, so after switching tabs, when I want to find the tab with the search for "Chocolate Ice Cream", I have to look for the tab named "Firefox 41".

Thank you for your attention!

**Comment by erichgoldman** [comment]
Thank you for reporting your specific examples. I have replicated the Adblock plus issue and will debug. Can you please let me know which search engine and with what URLS, etc. (please open a new ticket so I can track the one separate - one ticket for each example makes it easier). 

Based upon the JavaScript and other dynamic activity on page, this types of things can happen [(See FAQ)](https://github.com/erichgoldman/add-url-to-window-title/wiki/Frequently-Asked-Questions#there-seems-to-be-characters-stripped-out-of-the-title-and-it-interferes-with-my-existing-auto-type-matching-rules). 

I will investigate these specific examples to see if I can detect why they are not working. In development I am looking at a technique which would do more updates that may address these types of issues, however, it adds to overhead and could slow down all pages, etc. I have concerns over decreasing performance, but if these issues come from something else I can fix then we will see what I can do.

**Comment by teresaejunior** [comment]
Thank you for your answer, I have created issue #7 for the search engine!

**Comment by teresaejunior** [comment]
This bug (together with #7) was happening on Firefox 40, but doesn't seem to happen on Nightly 44.0a1!

**Comment by erichgoldman** [comment]
Okay, I will continue to track this. I am going to put this hold on fix until release 44 is out, they may have addressed something in the underlying processing that addresses this. If not, I will re-evaluate the more resource intensive solution I have in an offline test environment. Thank you for your report.

**Comment by teresaejunior** [comment]
OK, thanks!

**Comment by stonecrusher** [comment]
As the problem still exists in Firefox 50.0, I wanted to add that the full URL, which is added to the title by this addon, in fact does change. Just the title coming from the website itself does not update. It will update when pressing F5.

**Comment by erichgoldman** [comment]
Since Mozilla is [moving to the new add-on framework](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/) I will not be making further updates in this branch. I am learning the new framework and will release a new version on that framework. The good news is the plugin will hopefully be one package that works on FF, Chrome, and others. We will see if this problem persists in the new framework. Since the code operates differently we may have completely different issues.

**Comment by erichgoldman** [comment]
Hello @teresaejunior , I have released a new version for modern Firefox, can you please [update](https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/) and let me know if the problem still persists?
