### ISSUE TITLE
Window/Tab title not updated on searx.me

### ISSUE THREAD

**Issue by admirabilis** [erichgoldman/add-url-to-window-title#7]
As requested on issue #6, this is a way to reproduce the "title not updated" problem on searx.me:
- Add searx.me to your searchbar:
  1. Install the addon "Add to Search Bar"
  2. Visit: https://searx.me/
  3. Right click in the search field at searx.me and add it to your searchbar.
- Now do a search **from the search bar** for "Firefox 41" using searx
- Title: Firefox 41 - searx - searx.me/ - Firefox
- From within searx, do a web search from its **internal search field** for the words "Chocolate Ice Cream"
- Title: **Firefox 41** - searx - searx.me/ - Firefox

If you skip step one and search directly from searx.me, the title will always be: "searx - searx.me/ - Firefox", but it should be "%s - searx - searx.me/ - Firefox" instead!

**Comment by erichgoldman** [comment]
See comments in #6 . Tracking changes as of release 44 to see if underlying OS changes will help the flow and order of processing.

**Comment by erichgoldman** [comment]
`Repo Maintenance` I am closing tickets for specific sites that are more than three years old, as those sites are likely different now and the problems may no longer exist. If this is still an issue with a modern browser version and the current version of the add on, please response and we can reopen the ticket.
