### ISSUE TITLE
Printing problem, duplicated URL (other addon involved)

### ISSUE THREAD

**Issue by e13bb4dac2** [erichgoldman/add-url-to-window-title#9]
Hello, I have some printing problems from time to time. At last I figured out why, now I'm just missing the how :)

Print Edit 16.4 and
Add URL to Window Title 1.01 disabled
Firefox 44.0.2, Windows 10.

Address bar URL:
https://plex.tv/

Tab name/tooltip/title:
"Plex: Your media on all your devices" (same having all add-ons disabled)

**1. Print Edit enabled**

**1.2 Tab name/tooltip/title:**
Plex: "Your media on all your devices"

**2. Print Edit print dialog title:**
"Plex: Your media on all your devices - Mozilla Firefox" (this string is sent to the printer/print job name, " - Mozilla Firefox" is added to the actual tab name content)

**3. Add URL to Window Title 1.01 enabled**

**3.1 Tab name/tooltip/title:**
"Plex: Your media on all your devices - https://plex.tv/"

**3.2 Print Edit print dialog title:**
"Plex: Your media on all your devices  - https://plex.tv/ - https://plex.tv/ - Mozilla Firefox"

When the base title content is very long, the duplicated (when unusually long) URL + " - Mozilla Firefox" makes a printout fail using Print Edit. No error from the printer, the windows print manager/queue just stalls and eventually clears. No options in Print Edit.

Example:

http://www.skatteverket.se/funktioner/kalenderarkiv/2016privat/14mars.5.3810a01c150939e893f14fd.html

end up as

`2016 års kalender för privatpersoner | Skatteverket - http://www.skatteverket.se/funktioner/kalenderarkiv/2016privat/14mars.5.3810a01c150939e893f14fd.html - http://www.skatteverket.se/funktioner/kalenderarkiv/2016privat/14mars.5.3810a01c150939e893f14fd.ht`

note the 2 last characters of .html and " - Mozilla Firefox" is missing (string len limit?). I can't print this page using Print Edit - but it does work using the basic native (ctrl+p) print dialog.

Solution; disable/don't use/talk to Print Edit?

Well, yes. But..

As expected (according to **2.**), print Edit will add " - Mozilla Firefox". That's OK! What I can't figure out is why the URL is duplicated, having Add URL to Window Title 1.01 enabled? Is it all on Print Edit or is your (great) add-on somehow shooting twice? :)

Cheers

Edit: formatting error due to quotes wrecked the underline tag

**Comment by erichgoldman** [comment]
Hello,

Add URL to Window Title (AUtWT) checks for updates or changes on the page. This is necessary for single page applications and for named anchor links / hashes links (e.g., `something.html#someref`).

There[ is a check to see if the title already includes the URL](https://github.com/erichgoldman/add-url-to-window-title/blob/master/data/add-url-to-title.js#L219). But if there is heavy JavaScript this can cause issues.

I am not sure what is meant by "Print Edit enabled" If I go to the `File` menu and then select `Print` or `Print Preview` on that website I am not getting a URL duplication. I think maybe there is an internationalization or language difference here. Can you post a series of screenshots or a gif video of a screencast so I can better understand which menus you are accessing. I was not able to replicate from the above.

I am testing on `44.0.1` I will test on `44.0.02` with a fresh install. I do not have Windows 10, so there may be an issue there.

The way that this addon works is by modifying the actual `<title />` tag. The part where `- Mozilla Firefox` is added can also be edited, but that was not a stable API. Mozilla is moving to a similar style of plugins as used in Chrome, so I am not actively updating this version as this type of plugin may loose support. However, if I can replicate and fix I will issue an update.

Thanks for reporting this issue and for posting the review on the Mozilla Add-On site! Hopefully we can get this fixed.

**Comment by e13bb4dac2** [comment]
Hello,

I'm sorry for not being clear (addon mention in subject only) about Print Edit! Here's the link to the Print Edit addon:
[https://addons.mozilla.org/sv-SE/firefox/addon/print-edit/](url)

**Comment by erichgoldman** [comment]
Hello,

I download the source for the Print Edit! extension. I did  a quick search and it looks like that extension also does manipulations of the title field. There is no real way for the two extensions to communicate. I will see if there is something that can be done that would detect this. However, I think for the time being you will have to disable Add URL to Window Title when you want to use this print functionality.

**Comment by e13bb4dac2** [comment]
Thanks for input - I'll keep saving as pdf for now (whenever I need to edit a print) and attempt to contact the author of Print Edit and point him/her to this thread. With luck there's a simple fix for this issue from his end of things, perhaps best of all an option to skip changes to title data and/or set a max string length, alternatively parsing out title URLs altogether.

Thanks again!

Will update when/if sorted out in the near future

**Comment by e13bb4dac2** [comment]
Here's a some pictures. I have also linked to this thread here:
[https://addons.mozilla.org/en-US/firefox/addon/print-edit/reviews/779933/](https://addons.mozilla.org/en-US/firefox/addon/print-edit/reviews/779933/)

![au2wtpe](https://cloud.githubusercontent.com/assets/17198964/13053387/89be53fe-d404-11e5-9828-03eb011f4ad8.png)
